Repository cse110-sp23-group30/cse110-sp23-group30, pull requests merged in 2023-04, with the labels that each got.

#7 Add shake animation
  admin/8ball/app.js
  admin/8ball/styles.css
  admin/8ball/testing.html
Labels: documentation

#8 Animation + text box + message adjust
  admin/8ball/app.js
  admin/8ball/styles.css
  admin/8ball/testing.html
Labels: documentation

#10 Magic8 second update
  admin/8ball/app.js
  admin/8ball/media/empty.txt
  admin/8ball/media/magic8-image1.png
  admin/8ball/styles.css
  admin/8ball/testing.html
Labels: enhancement

#12 PLEASD READ PULL REQUEST! added invis override buttons, added z-index
  admin/8ball/app.js
  admin/8ball/styles.css
  admin/8ball/testing.html
Labels: enhancement

#13 updated override functions in app.js
  admin/8ball/app.js
Labels: enhancement

#14 added some documentations
  admin/8ball/app.js
  admin/8ball/styles.css
  admin/8ball/testing.html
Labels: documentation

#15 Min
  admin/8ball/app.js
  admin/8ball/styles.css
  admin/8ball/testing.html
Labels: enhancement

#16 Changed the hidden buttons so that they don't overlap the main button…
  admin/8ball/app.js
  admin/8ball/styles.css
  admin/8ball/testing.html
Labels: bug, enhancement
