Repository cse110-sp23-group30/cse110-sp23-group30, pull requests merged in 2023-06, with the labels that each got.

#95 close to final instruction screen update
  source/instruction_screen/BOWL&PLATE.png
  source/instruction_screen/COOKIE.png
  source/instruction_screen/ITEM.png
  source/instruction_screen/instruction.css
  source/instruction_screen/instruction.html
  source/instruction_screen/instruction.js
Labels: enhancement, Screens

#98 Feature/cart screen/sprint 3
  source/assets/Beijing-Beef.jpg
  source/assets/Broccoli-Beef.jpg
  source/assets/Chow-Mein.jpg
  source/assets/Fried-Rice.jpg
  source/assets/Honey-Walnut-Shrimp.jpg
  source/assets/Kung-Pao-Chicken.jpg
  source/assets/Orange-Chicken.jpg
  source/assets/Veggies.jpg
  source/assets/pandalogo.png
  source/assets/pandanologo.png
  source/bowl-screen/bowl-screen.css
  source/bowl-screen/bowl-screen.html
  source/bowl-screen/bowl-screen.js
  source/cart_screen/cart.css
  source/cart_screen/cart.html
  source/cart_screen/cart.js
  source/centralized css/centralized.css
  source/header/header-component.js
  source/header/index.html
Labels: Screens

#103 Fixed a lot of bugs
  source/bowl-screen/Panda-Express-Beef-and-Broccoli.jpg
  source/bowl-screen/Panda-Express-Chow-Mein.jpg
  source/bowl-screen/Panda-Express-Fried-Rice.jpg
  source/bowl-screen/bowl-screen.html
  source/bowl-screen/bowl-screen.js
  source/bowl-screen/panda-express-beijing-beef.jpg
  source/bowl-screen/panda-express-honey-walnut-shrimp.jpg
  source/bowl-screen/panda-express-kung-pao-chicken.jpg
  source/bowl-screen/panda-express-orange-chicken.jpg
  source/bowl-screen/panda-express-veggies.jpg
  source/cart_screen/cart.css
  source/cart_screen/cart.html
  source/cart_screen/cart.js
  source/cookie_screen/cookie_screen.html
  source/cookie_screen/cookie_screen.js
  source/instruction_screen/instruction.css
  source/instruction_screen/instruction.html
  source/opening_screen/opening-screen.html
  source/plate-screen/Panda-Express-Beef-and-Broccoli.jpg
  source/plate-screen/Panda-Express-Chow-Mein.jpg
  source/plate-screen/Panda-Express-Fried-Rice.jpg
  source/plate-screen/panda-express-beijing-beef.jpg
  source/plate-screen/panda-express-honey-walnut-shrimp.jpg
  source/plate-screen/panda-express-kung-pao-chicken.jpg
  source/plate-screen/panda-express-orange-chicken.jpg
  source/plate-screen/panda-express-veggies.jpg
  source/plate-screen/pandanologo.png
  source/plate-screen/plate-screen.css
  source/plate-screen/plate-screen.html
  source/plate-screen/plate-screen.js
Labels: bug, Screens

#145 Plate and bowl screen updates
  source/bowl-screen/bowl-screen.html
  source/bowl-screen/bowl-screen.js
  source/plate-screen/plate-screen.css
  source/plate-screen/plate-screen.html
  source/plate-screen/plate-screen.js
Labels: enhancement

#154 Feature/cart screen/testing
  jest.config.js
  package.json
  source/cart_screen/cart.html
  source/cookie_screen/cookie_screen.css
  source/cookie_screen/cookie_screen.html
  source/tests/cart.test.js
  source/tests/instruction.test.js
  source/tests/opening.test.js
Labels: Screens, testing

#165 fortune cookie sound effect
  source/assets/Wow.mp4
  source/cookie_screen/cookie_screen.html
  source/cookie_screen/cookie_screen.js
Labels: enhancement
